### ISSUE TITLE
adding articles to the website?

### ISSUE THREAD

**Issue by cremno** [mruby/mruby.github.io#17]
Maybe helpful and interesting articles like @bovi's [Five ways to execute mruby](http://blog.mruby.sh/201207020720.html) should be updated and added to the website?

I would help with that or do it on my own unless @bovi doesn't want it or people disagree with this idea.

**Comment by bovi** [comment]
If there is any interest I'm more than happy. But the article is quite old and needs definitly some refresh.

**Comment by cremno** [comment]
I haven't updated the whole article yet and I think I'm going to merge articles into documentation. Also apparently code highlighting in posts is as hard as understanding floating-point math or naming things. Well, it isn't that important.

![mrubyarticletest](https://cloud.githubusercontent.com/assets/212792/7665388/bd7ef6ae-fbb4-11e4-9320-7e18b03e4450.png)

**Comment by bovi** [comment]
Great work. I think it is a good idea to put it under documentation. I think I have to have a look again on this mrbdoc tool so that we can regular update the reference API.

I think code highlighting can be done later.

**Comment by matz** [comment]
Looking forward to the update.

**Comment by cremno** [comment]
See #21 for a revamp of @bovi's blog post.

Also: If anyone here knows other existing articles (or ones that don't but definitely should) tell me / us.

**Comment by cremno** [comment]
@bovi: What do you think about linking the article in your blog post, so people are aware that it's outdated and current examples are available?

**Comment by bovi** [comment]
@cremno sure thing. will do the change

**Comment by zzak** [comment]
Seems like this was resolved, so giving it a close.

Thanks for updating the article @cremno! <3
