### ISSUE TITLE
Content issue with article "executing-ruby-code-with-mruby"

### ISSUE THREAD

**Issue by hlogmans** [mruby/mruby.github.io#40]
Some time ago I followed the mentioned tutorial. But the last part (Bytecode (.c)) seems to be a bit confusing for a beginner:

This line: "To execute this bytecode the following boilerplate has to be written:" 
I think the most straightforward tip for beginners is to write a file "test_main.c" with this code, and add a include to "test_program". This way, if the generated code is updated everything can be kept. (I was confused as where to add the boilerplate code, and could not get it working together with the array.)

Then the compile command is:
`````
gcc -std=c99 -Imruby/include test_main.c test_program.c -o test_program.o  mruby/build/host/lib/libmruby.a
````

This makes this example just a bit more specific so an experimenting user only has to follow this tutorial exactly.

**Comment by matz** [comment]
Could you send us a pull-request?

**Comment by hlogmans** [comment]
#43
