### ISSUE TITLE
News about 1.4 release is missing from the website

### ISSUE THREAD

**Issue by graywolf** [mruby/mruby.github.io#59]
Latest news on http://mruby.org/ is 1.3.0 released despite 1.4.1 being already out. That seems a bit confusing. Probably would be good idea to write at least short notice saying `Hey, 1.4.1 is out.` so it looks more up to date. Having `What’s new in mruby 1.4.{0,1}` would be nice too but I'm not qualified to write that...

**Comment by bovi** [comment]
sorry, I promised to create an article quite some time ago but had no time in the last couple of months. it also seems my ssl certificate is out of dat 🙄 I do during my holiday in the next days if no one else has fixed it unil then 🤗

**Comment by bovi** [comment]
was now merged.
