### ISSUE TITLE
Is it possible to CNAME `ci.mruby.org` to mrbgem CI?

### ISSUE THREAD

**Issue by take-cheeze** [mruby/mruby.github.io#61]
I'm currently maintaining CI for mgem-list and mruby in:
https://103.128.221.202.static.iijgio.jp/jenkins/

**Comment by mattn** [comment]
![tenor](https://user-images.githubusercontent.com/10111/47079826-5b397700-d241-11e8-864f-8bfdd413ba5f.gif)

**Comment by matz** [comment]
Should we direct `ci.mruby.org` to `103.128.221.202.static.iijgio.jp`?

**Comment by take-cheeze** [comment]
For now that seems to be enough.

**Comment by matz** [comment]
Done. Could you confirm?

**Comment by take-cheeze** [comment]
Thanks!
Seems redirecting. I'll fix the nginx config.

**Comment by take-cheeze** [comment]
Now it should work:
https://ci.mruby.org/jenkins/
