### ISSUE TITLE
mruby.org has a JavaScript error for missing jQuery

### ISSUE THREAD

**Issue by jbampton** [mruby/mruby.github.io#83]
<img width="847" alt="Screen Shot 2020-12-22 at 7 45 32 pm" src="https://user-images.githubusercontent.com/418747/102874842-b9e88400-448e-11eb-83d4-cdb7eb95384e.png">

**Comment by matz** [comment]
It seems it's fixed by f64a4cca3a15b2a431aed4f594b7860d061e2268
